agregamos contenido sesion 1
saitcmty/pumm-web pull request #21
Opened 2021-03-29 21:28 UTC by gabrielacorona

agregamos el contenido de la sesión 1
- presentación de drive
- quiz del forms

2021-04-03 05:38 UTC, ncgo requested changes
Hay algunos detallitos que ya están comentados :)

2021-04-03 05:38 UTC, ncgo commented on fj-21/avanzados/sesion1.html
> +  <link href="../libraries/dist/css/bootstrap.min.css" rel="stylesheet">
El estilo de la página no está apareciendo, creo que tiene que ver con la forma en que están accesando los archivos con los relative paths

2021-04-03 05:38 UTC, ncgo commented on fj-21/avanzados/sesion1.html
> +          <p class="lead text-justify">HTML es un lenguaje de marcado para la elaboración de páginas web. Un estándar
Actualizar de qué trata la sesión de avanzados, específicamente lo que se vió ese día.

2021-04-03 05:38 UTC, ncgo commented on fj-21/avanzados/sesion1.html
> +          <p class="lead">Encuentra el manual de instalación de Atom, el editor de texto que estaremos utilizando, dando
No utilizaremos Atom, es repl.it. Si gustan agregar la guía de uso que creamos estaría perfecto. La pueden encontrar en el drive

2021-04-03 05:38 UTC, ncgo commented on fj-21/avanzados/sesion1.html
> +              href="https://drive.google.com/file/d/1c-wiyo8nTxRTEWGxl4L43YU5wLfPAeQB/view?usp=sharing"><strong>Link a
También hay que actualizar la liga a la grabación, la pueden encontrar en el drive en la carpeta de su sesión

2021-04-03 05:38 UTC, ncgo commented on fj-21/avanzados/sesion1.html
> +          src="https://docs.google.com/presentation/d/1FSZUH5Hn3ciM_tHhZmK25eLN1BDZCYNvTVB3aXRKEiM/edit?usp=sharing"
Hay que revisar que la liga sea la correcta, me aparecen las opciones de editar la presentación y solo queremos que se vea la info

2021-04-13 15:27 UTC, Juanpabdl commented
Inclui los cambios en la página, usamos el formato que nos dijeron

2021-04-23 03:38 UTC, juliocesar1235 approved these changes

2021-04-23 04:08 UTC, ncgo approved these changes

2021-04-23 04:08 UTC, merged