Fj21 princ sesion8
saitcmty/pumm-web pull request #30
Opened 2021-05-25 03:19 UTC by fernymart

Listo, cualquier error me avisan :)

2021-05-25 07:19 UTC, ncgo requested changes

2021-05-25 07:19 UTC, ncgo commented on fj-21/principiantes/sesion8.html
> +        <h1 class="text-center pb-3">Introducción a JavaScript/h1>
Etiqueta no cerrada

2021-05-25 23:29 UTC, fernymart commented on fj-21/principiantes/sesion8.html
> +        <h1 class="text-center pb-3">Introducción a JavaScript/h1>
Listo :)

2021-05-26 03:33 UTC, ncgo commented on fj-21/principiantes/sesion8.html
> +        <h1 class="text-center pb-3">Introducción a JavaScript/h1>
gracias!

2021-05-26 03:33 UTC, ncgo approved these changes

2021-05-26 03:34 UTC, merged